sudo: false
language: ruby
services:
  - docker
before_install:
  - git clone --depth 1 https://github.com/seiferma/Docker_BuildUtils.git /tmp/BuildUtils
  - . /tmp/BuildUtils/travisSetup.sh
script:
  - travisBuildDockerhub.sh
deploy:
  provider: script
  script: travisDeployDockerhub.sh
  on:
    branch: master
env:
  global: 
    - IMAGE_NAME=seiferma/httpd-static
    - secure: "WasM1lhlkwMdb2WDCLCP+YDgaFUkkLpTSNGrT9+U6KY70hatfwsUInS2r4uC9Lf6D17cCaYUlrSOwNYJQWK1WRCIbenDzDLIfD4NKXzuQ88wboxva6MwjewiGJ1lEVyTQzye1Z7rDwHU2c7LbWvqEof8wncCe3i98K9EWa2Lc0t55jSV5fDjyjaVoX1JvqlD8rb/6I0o2qTEij/ka1cIe7GeCEcYv9CGnr0JYnU+BQPKn1t57NwDn4wH3I2JgtK0AiBIsttWabzJzBcRN5AKQvG1jE5tYCw8kaAIj8TL2OiCjlnZrE31lu6XmCK9i0gFItRPlV1hnTg2FowPis5oNPLc3xwSUrpdKDbLKJeNYWvTqdeBuTfEExTxKa8pNUta+TOdZGp3w5Ht6PJSjDYXAWC9mIPJ1nWcz7odn8KyWfLeOT8s15MeRE42BR4pP968IRTthTH8EcFWSnfuUlnXa7AQ4J6TjSuf1M6UwmhE5gnidJtXN7Si3PE9tyiMN/tnSMoyJirANk8WqrYUsvRDSuPREZRAeAgbQ6cyclu78iyUdmmTU9lRJd+2JRLABekc2Y9i4L5TcGbUGyaR2p5JUJ72KZ1Nw3cqpL47fhwyvrs/8k6PsIb4MsSlEabaMnksWtjznjDs433PL/mL+OUKkDMXewEFlv39ndLNWi7KYw0="
